import { Router } from "express";
import { authenticate } from "../middleware/authenticate";
import { authorize } from "../middleware/authorize";
import { adminOverview, deleteAdminComplaint, deleteResident, listAdminComplaints, listAdminFeedback, listAdminFeedbackSummary, listAdminSchedules, listAdminVoteSummary, listAdminVotes, listAdminZones, listResidents, updateAdminComplaint, updateAdminProfile, updateResidentStatus } from "../controllers/adminController";

const router = Router();
router.use(authenticate, authorize("admin"));
router.get("/overview", adminOverview);
router.get("/zones", listAdminZones);
router.get("/schedules", listAdminSchedules);
router.get("/residents", listResidents);
router.patch("/residents/:id/status", updateResidentStatus);
router.delete("/residents/:id", deleteResident);
router.get("/complaints", listAdminComplaints);
router.patch("/complaints/:id", updateAdminComplaint);
router.delete("/complaints/:id", deleteAdminComplaint);
router.get("/votes", listAdminVotes);
router.get("/votes/summary", listAdminVoteSummary);
router.get("/feedback", listAdminFeedback);
router.get("/feedback/summary", listAdminFeedbackSummary);
router.patch("/profile", updateAdminProfile);
export default router;
