import type { Request,Response,NextFunction } from "express"; import bcrypt from "bcryptjs"; import { User } from "../models/User"; import { Zone } from "../models/Zone"; import { EmailOtp } from "../models/EmailOtp"; import { ApiError } from "../utils/ApiError"; import { signToken } from "../utils/jwt"; import { sendPasswordResetOtp,sendVerificationOtp } from "../utils/email"; import type { AuthRequest } from "../middleware/authenticate";
const safeUser=(user:any)=>({_id:user._id,name:user.name,email:user.email,phone:user.phone,address:user.address,role:user.role,emailVerified:user.emailVerified,accountStatus:user.accountStatus,profileImage:user.profileImage,zoneId:user.zoneId});
async function createOtp(email:string){const code=Math.floor(100000+Math.random()*900000).toString();await EmailOtp.findOneAndUpdate({email},{email,codeHash:await bcrypt.hash(code,10),expiresAt:new Date(Date.now()+10*60*1000),attempts:0},{upsert:true,new:true,setDefaultsOnInsert:true});return code;}
async function createAndSendOtp(email:string){await sendVerificationOtp(email,await createOtp(email));}
export async function register(req:Request,res:Response,next:NextFunction){try{const {name,password,phone,address,zoneId,profileImage}=req.body;const email=String(req.body.email).trim().toLowerCase();if(!await Zone.exists({_id:zoneId,isActive:true}))throw new ApiError(400,"Select an active zone");const existing=await User.findOne({email});if(existing?.emailVerified)throw new ApiError(409,"An account already uses this email");const values={name,phone,address,password:await bcrypt.hash(password,12),zoneId,profileImage:profileImage||existing?.profileImage||""};if(existing){Object.assign(existing,values);await existing.save();}else await User.create({email,...values});await createAndSendOtp(email);res.status(201).json({data:{email,message:"Verification code sent to your email"}});}catch(e){next(e);}}
export async function verifyEmail(req:Request,res:Response,next:NextFunction){try{const {email,code}=req.body;const otp=await EmailOtp.findOne({email});if(!otp||otp.expiresAt<new Date())throw new ApiError(400,"Verification code is invalid or expired");if(otp.attempts>=5)throw new ApiError(429,"Too many attempts. Request a new code.");if(!(await bcrypt.compare(code,otp.codeHash))){otp.attempts+=1;await otp.save();throw new ApiError(400,"Verification code is invalid or expired");}const user=await User.findOneAndUpdate({email},{emailVerified:true},{new:true});if(!user)throw new ApiError(404,"User not found");await otp.deleteOne();res.json({data:{token:signToken({userId:user.id,role:user.role}),user:safeUser(user)}});}catch(e){next(e);}}
export async function resendOtp(req:Request,res:Response,next:NextFunction){try{const user=await User.findOne({email:req.body.email});if(!user)throw new ApiError(404,"User not found");if(user.emailVerified)throw new ApiError(400,"This email is already verified");await createAndSendOtp(user.email);res.json({data:{message:"A new verification code was sent"}});}catch(e){next(e);}}
export async function login(req:Request,res:Response,next:NextFunction){try{const {password}=req.body;const email=String(req.body.email).trim().toLowerCase();const user=await User.findOne({email}).select("+password");if(!user||!(await bcrypt.compare(password,user.password)))throw new ApiError(401,"Invalid email or password");if(!user.emailVerified)throw new ApiError(403,"Verify your email before signing in");if(user.accountStatus==="suspended")throw new ApiError(403,"This account is suspended");res.json({data:{token:signToken({userId:user.id,role:user.role}),user:safeUser(user)}});}catch(e){next(e);}}
export async function forgotPassword(req:Request,res:Response,next:NextFunction){try{const user=await User.findOne({email:req.body.email});if(user){await sendPasswordResetOtp(user.email,await createOtp(user.email));}res.json({data:{email:req.body.email,message:"If this email is registered, a password reset code was sent"}});}catch(e){next(e);}}
export async function resetPassword(req:Request,res:Response,next:NextFunction){try{const {email,code,password}=req.body;const otp=await EmailOtp.findOne({email});if(!otp||otp.expiresAt<new Date())throw new ApiError(400,"Reset code is invalid or expired");if(otp.attempts>=5)throw new ApiError(429,"Too many attempts. Request a new code.");if(!(await bcrypt.compare(code,otp.codeHash))){otp.attempts+=1;await otp.save();throw new ApiError(400,"Reset code is invalid or expired");}const user=await User.findOneAndUpdate({email},{password:await bcrypt.hash(password,12),emailVerified:true},{new:true});if(!user)throw new ApiError(404,"User not found");await otp.deleteOne();res.json({data:{token:signToken({userId:user.id,role:user.role}),user:safeUser(user)}});}catch(e){next(e);}}
export async function me(req:AuthRequest,res:Response,next:NextFunction){try{const user=await User.findById(req.auth!.userId).populate({path:"zoneId",select:"-imageBase64"});if(!user)throw new ApiError(404,"User not found");res.json({data:safeUser(user)});}catch(e){next(e);}}
